name: Receiving push from depenency
on:
  repository_dispatch:
    types: [my-event]

jobs:
  run-based-on-event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo running build with sha=${{ github.event.client_payload.sha }}

